backend: cmd
working_dir: .reme

metadata:
  max_iters: 50
  context_window_tokens: 100000
  reserve_tokens: 30000
  keep_recent_tokens: 10000
  vector_weight: 0.7
  candidate_multiplier: 2
  skills_repo_url: https://github.com/zouyingcao/finance-skills.git

as_llms:
  default:
    backend: openai
    model_name: glm-5.1

as_llm_formatters:
  default:
    backend: openai

as_token_counters:
  default:
    backend: hf
    pretrained_model_name_or_path: Qwen/Qwen3-Coder-30B-A3B-Instruct
    use_mirror: true

embedding_models:
  default:
    backend: openai
    model_name: text-embedding-v4
    dimensions: 1024
    enable_cache: true
    use_dimensions: false

file_stores:
  default:
    backend: chroma
    #    backend: local
    store_name: reme
    embedding_model: default
    fts_enabled: true
    vector_enabled: true

file_watchers:
  default:
    backend: full
    file_store: default
    watch_paths: [ ".reme", ".reme/memory" ]
    suffix_filters: [ ".md" ]
    recursive: false
    scan_on_start: true

